----
- name: Install MongoDB
  hosts: all
  become: true
  tasks:
    - name: Add APT key
      apt_key:
        id: EA312927
        keyserver: keyserver.ubuntu.com
    - name: Add APT repository
      apt_repository:
        repo: deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/4.2 multiverse
        state: present
        filename: mongodb-org-4.2
        update_cache: yes
    - name: Install mongodb package
      apt:
        name: mongodb-org
        state: present
        update_cache: yes
        allow_unauthenticated: yes
    - name: Configure service supervisor
      systemd:
        name: mongod
        enabled: yes
